# Generated by Django 4.0.7 on 2022-10-08 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_patient', models.CharField(max_length=200)),
                ('neurological', models.IntegerField()),
                ('MeaningNeurological', models.CharField(max_length=200)),
                ('cardiovascular', models.IntegerField()),
                ('MeaningCardiovascular', models.CharField(max_length=200)),
                ('respiratory', models.IntegerField()),
                ('MeaningRespiratory', models.CharField(max_length=200)),
                ('coagulation', models.IntegerField()),
                ('MeaningCoagulation', models.CharField(max_length=200)),
                ('hepatic', models.IntegerField()),
                ('MeaningHepatic', models.CharField(max_length=200)),
                ('renal', models.IntegerField()),
                ('MeaningRenal', models.CharField(max_length=200)),
                ('spict', models.IntegerField()),
                ('MeaningSpict', models.CharField(max_length=200)),
                ('ecog', models.IntegerField()),
                ('MeaningEcog', models.CharField(max_length=200)),
                ('scoreSOFA', models.IntegerField()),
                ('scoreAmib', models.IntegerField()),
                ('group_patient', models.IntegerField()),
                ('classification', models.IntegerField()),
                ('active', models.BooleanField()),
                ('exported', models.BooleanField()),
                ('validatedDoctor', models.IntegerField()),
                ('justification', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
    ]
