# Generated by Django 4.1.2 on 2022-10-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapatient',
            name='justification',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='datapatient',
            name='validatedDoctor',
            field=models.IntegerField(null=True),
        ),
    ]
